### ISSUE TITLE
Name error in feeds.conf

### ISSUE THREAD

**Issue by VincentMVG** [nickberry17/luci-proto-modemmanager#2]
Hello,

I'm having some trouble with your instructions.
When I add the line in feeds.conf and update the feeds I have this message:
Syntax error in feeds.conf, line: 5

If I change the name luci-proto-modemmanager to luci_proto_modemmanager it works

**Comment by nickberry17** [comment]
Hi, thanks for pointing that out.  The error is because the feeds file cannot have dashes in the feed name.  Resolved.
