### ISSUE TITLE
luci-proto-modemmanager not included in image

### ISSUE THREAD

**Issue by jrvanator** [nickberry17/luci-proto-modemmanager#4]
Strangest thing.  I'm compiling the lastest master with the feeds updated and installed, included modemmanager and luci-proto-modemmanager in menuconfig, everything compiles clean.   I even see luci-proto-modemmanager is the make output.

However, when I load the new image and do a opkg list, luci-proto-modemmanager is not present.   modemmanager itself is loaded and working fine.

Any suggestions?

**Comment by jrvanator** [comment]
Small addendum....I noted that luci-proto-modemmanager is in the packages feed, however, it doesn't show up in menuconfig unless you include the discrete feed.....but it still isn't included in the build directories or the final image.

**Comment by ysoyipek** [comment]
> Küçük Zeyilname .... Luci-proto-modemmanager'in paket beslemesinde olduğunu, ancak ayrı beslemeyi dahil etmediğiniz sürece menuconfig'te görünmediğini belirtmiştim ..... dizinler veya son görüntü oluşturmak.

I have that same problem. Did you find the solution? Can you explain?

**Comment by nickberry17** [comment]
It is not currently supported in master, only in OpenWrt 18 and below.  Support for master requires a rewrite in Javascript

**Comment by wicadmin** [comment]
@nickberry17 - This is broken in Snapshot. Mobile Data is an unrecognized protocol.
